name: release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # required for OIDC
  contents: write # required to commit & push changes
  pull-requests: write # required to open/update PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Clear auth token for OIDC
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV

      - name: Upgrade NPM
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: pnpm install

      - name: Debug Node/NPM
        run: |
          node -v
          npm -v
          which npm
          npm config get registry

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: "release: update cli version"
          title: "release: update cli version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: "" # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
